#difference
a={1,2,3,4}
b={1,2,3}
print(a)
print(a.difference(b))
print(a-b)
print(a)
print("="*50)
#differenc_update
c={1,2,3,4}
d={1,2,3}
print(c)
c.difference_update(d)
print(c)
print("="*50)
#intersection
e={1,2,3,4,"x"}
f={"osama","x",1}
print(e)
print(e.intersection(f))
print(e&f)
print("="*50)
#intersection update
g={1,2,3,4,"x"}
k={"osama","x",1}
print(g)
g.intersection_update(k)
print(g)
print(g& k)
print("="*50)
#symmetric_difference
i={1,2,3,4,"x"}
j={"osama","x",1,2}
print(i)
print(i.symmetric_difference(j))
print("="*50)
#symmetric_difference
m={1,2,3,4,"x"}
n={"osama","x",1,2}
print(i)
m.symmetric_difference_update(n)
print(m)
print("="*50)
#boolen method
o={1,2,3,4}
p={1,2,3}
q={1,2,3,5}
print(o.issuperset(b))
print(o.issuperset(q))
print("="*50)
r={1,2,3}
y={1,2,3,4}
i={1,2,5}
print(r.issubset(y))
print(r.issubset(i))
print("="*50)
s={1,2,3,4}
v={10,20,30}
print(s.isdisjoint(v))